### ISSUE TITLE
MMC crash Chip_I2C_SlaveStateHandler

### ISSUE THREAD

**Issue by gustavosr8** [lnls-dig/openMMC#160]
Sometimes the MMC firmware crashes in the Chip_I2C_SlaveStateHandler function. With a dump of program counter and stack pointer values before the crash, we can see that it occurs in the line 541. One hypothesis is that the id value is out of range, but needs more investigation.

**Comment by gustavosr8** [comment]
This is a GDB Backtrace with a Dummy handler (`I2C_Dummy_event`) to the `I2C_SLAVE_GENERAL` address.

```
I2C_Dummy_Event (id=<optimized out>, event=<optimized out>)
    at /home/ABTLUS/gustavo.reis/repos/openMMC/port/ucontroller/nxp/lpc17xx/lpc17_i2c.c:146
(gdb) bt
#0  I2C_Dummy_Event (id=<optimized out>, event=<optimized out>)
    at /home/ABTLUS/gustavo.reis/repos/openMMC/port/ucontroller/nxp/lpc17xx/lpc17_i2c.c:146
#1  <signal handler called>
#2  Chip_I2C_EventHandler (id=<optimized out>, event=I2C_EVENT_WAIT)
    at /home/ABTLUS/gustavo.reis/repos/openMMC/port/ucontroller/nxp/lpc17xx/lpcopen/src/i2c_17xx_40xx.c:35
0
#3  0x00009854 in Chip_I2C_MasterTransfer (id=id@entry=I2C0, xfer=xfer@entry=0x2007e298 <ucHeap+8856>)
    at /home/ABTLUS/gustavo.reis/repos/openMMC/port/ucontroller/nxp/lpc17xx/lpcopen/src/i2c_17xx_40xx.c:43
6
#4  0x000098c2 in Chip_I2C_MasterSend (id=id@entry=I2C0, slaveAddr=<optimized out>,
    buff=buff@entry=0x2007e2c9 <ucHeap+8905> "\020Єh\002\004\002\002\201Pô¥\245\245\245\245\245\245\245\24
5\245", len=len@entry=13 '\r')
    at /home/ABTLUS/gustavo.reis/repos/openMMC/port/ucontroller/nxp/lpc17xx/lpcopen/src/i2c_17xx_40xx.c:45
8
#5  0x00003aae in IPMB_TXTask (pvParameters=<optimized out>)
    at /home/ABTLUS/gustavo.reis/repos/openMMC/modules/ipmb.c:156
#6  0x00007000 in ?? ()

```
